import React from 'react';
import Link from 'next/link';

const Home: React.FC = () => (
  <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100vh', background: '#111', color: '#fff' }}>
    <h1 style={{ fontSize: 36, marginBottom: 32 }}>Sohith Real-Time Location Tracker</h1>
    <Link href="/vendor"><button style={{ margin: 8, padding: 12, fontSize: 18 }}>Vendor Dashboard</button></Link>
    <Link href="/delivery"><button style={{ margin: 8, padding: 12, fontSize: 18 }}>Delivery Dashboard</button></Link>
    <Link href="/track/123456"><button style={{ margin: 8, padding: 12, fontSize: 18 }}>Track Order (Sample)</button></Link>
    <p style={{ marginTop: 40, fontSize: 14, color: '#aaa' }}>This homepage was generated by Sohith on 28 May 2025.</p>
  </div>
);

export default Home;
